import { Box, FormControl, TextField, Typography } from '@mui/material'
import { grey } from '@mui/material/colors'
import { Stack } from '@mui/system'
import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Chart from '../chart/Chart'
import styles from '../styles/Home.module.css'

const url = "http://172.23.20.31:8000//"
const filename = "user001.csv"

export default function Home() {
  const [values, setValues] = useState<Number[]>([])

  useEffect(() => {
    const interval = setInterval(() => {
      axios
        .get(url + filename)
        .then((res) => {
          const arr = values.concat(res.data);
          setValues(arr)
        })
        .catch((err) => console.error(err))
    }, 2000)

    return () => clearInterval(interval)

  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Smart Pillow System</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className={styles.title}>
          Smart Pillow System
        </div>

        <div className={styles.grid}>
          <Box
            component="form"
            sx={{
              borderRadius: '10px',
              border: '1px solid',
              borderColor: grey[300],
              padding: '10px',
              margin: '50px',
              backgroundColor: grey[50],
            }}
            noValidate
            autoComplete="off"
          >
            <Stack direction="column" spacing={3} alignItems="center" justifyContent="center">
              <Typography variant="h5" component="div" style={{ fontWeight: '300' }}>Data Fetched</Typography>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Sleep Apnea</Typography>
                <TextField
                  variant="outlined"
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Temperature</Typography>
                <TextField
                  variant="outlined"
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Humidity</Typography>
                <TextField
                  variant="outlined"
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Stress</Typography>
                <TextField
                  variant="outlined"
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>SpO2</Typography>
                <TextField
                  variant="outlined"
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
            </Stack>
          </Box>
          <div>
            <Chart values={values} />
          </div>
        </div>
      </main>
    </div>
  )
}